# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vic/Desktop/wic/widgets/w_popup_calculator.ui'
#
# Created: Tue Sep 13 20:30:13 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WPopupCalculator(object):
    def setupUi(self, WPopupCalculator):
        WPopupCalculator.setObjectName(_fromUtf8("WPopupCalculator"))
        WPopupCalculator.resize(240, 152)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        WPopupCalculator.setPalette(palette)
        WPopupCalculator.setWindowTitle(QtGui.QApplication.translate("WPopupCalculator", "Калькулятор", None, QtGui.QApplication.UnicodeUTF8))
        WPopupCalculator.setStyleSheet(_fromUtf8("background-color: rgb(245, 245, 245);"))
        self.gridLayout = QtGui.QGridLayout(WPopupCalculator)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.display = QtGui.QLabel(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.display.setText(QtGui.QApplication.translate("WPopupCalculator", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.display.setTextFormat(QtCore.Qt.PlainText)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setMargin(3)
        self.display.setIndent(2)
        self.display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.display.setObjectName(_fromUtf8("display"))
        self.gridLayout.addWidget(self.display, 0, 0, 1, 6)
        self.digitButton_7 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_7.sizePolicy().hasHeightForWidth())
        self.digitButton_7.setSizePolicy(sizePolicy)
        self.digitButton_7.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_7.setText(_fromUtf8("7"))
        self.digitButton_7.setAutoRaise(True)
        self.digitButton_7.setObjectName(_fromUtf8("digitButton_7"))
        self.gridLayout.addWidget(self.digitButton_7, 1, 0, 1, 1)
        self.digitButton_8 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_8.sizePolicy().hasHeightForWidth())
        self.digitButton_8.setSizePolicy(sizePolicy)
        self.digitButton_8.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_8.setText(_fromUtf8("8"))
        self.digitButton_8.setAutoRaise(True)
        self.digitButton_8.setObjectName(_fromUtf8("digitButton_8"))
        self.gridLayout.addWidget(self.digitButton_8, 1, 1, 1, 1)
        self.digitButton_9 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_9.sizePolicy().hasHeightForWidth())
        self.digitButton_9.setSizePolicy(sizePolicy)
        self.digitButton_9.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_9.setText(_fromUtf8("9"))
        self.digitButton_9.setAutoRaise(True)
        self.digitButton_9.setObjectName(_fromUtf8("digitButton_9"))
        self.gridLayout.addWidget(self.digitButton_9, 1, 2, 1, 1)
        self.divideButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.divideButton.sizePolicy().hasHeightForWidth())
        self.divideButton.setSizePolicy(sizePolicy)
        self.divideButton.setMinimumSize(QtCore.QSize(24, 24))
        self.divideButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.divideButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Divide", None, QtGui.QApplication.UnicodeUTF8))
        self.divideButton.setText(_fromUtf8("÷"))
        self.divideButton.setAutoRaise(True)
        self.divideButton.setObjectName(_fromUtf8("divideButton"))
        self.gridLayout.addWidget(self.divideButton, 1, 3, 1, 1)
        self.squareRootButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.squareRootButton.sizePolicy().hasHeightForWidth())
        self.squareRootButton.setSizePolicy(sizePolicy)
        self.squareRootButton.setMinimumSize(QtCore.QSize(24, 24))
        self.squareRootButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.squareRootButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Square root", None, QtGui.QApplication.UnicodeUTF8))
        self.squareRootButton.setText(_fromUtf8("√"))
        self.squareRootButton.setAutoRaise(True)
        self.squareRootButton.setObjectName(_fromUtf8("squareRootButton"))
        self.gridLayout.addWidget(self.squareRootButton, 1, 4, 1, 1)
        self.backspaceButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backspaceButton.sizePolicy().hasHeightForWidth())
        self.backspaceButton.setSizePolicy(sizePolicy)
        self.backspaceButton.setMinimumSize(QtCore.QSize(24, 24))
        self.backspaceButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.backspaceButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.backspaceButton.setText(_fromUtf8("←"))
        self.backspaceButton.setAutoRaise(True)
        self.backspaceButton.setObjectName(_fromUtf8("backspaceButton"))
        self.gridLayout.addWidget(self.backspaceButton, 1, 5, 1, 1)
        self.digitButton_4 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_4.sizePolicy().hasHeightForWidth())
        self.digitButton_4.setSizePolicy(sizePolicy)
        self.digitButton_4.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_4.setText(_fromUtf8("4"))
        self.digitButton_4.setAutoRaise(True)
        self.digitButton_4.setObjectName(_fromUtf8("digitButton_4"))
        self.gridLayout.addWidget(self.digitButton_4, 2, 0, 1, 1)
        self.digitButton_5 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_5.sizePolicy().hasHeightForWidth())
        self.digitButton_5.setSizePolicy(sizePolicy)
        self.digitButton_5.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_5.setText(_fromUtf8("5"))
        self.digitButton_5.setAutoRaise(True)
        self.digitButton_5.setObjectName(_fromUtf8("digitButton_5"))
        self.gridLayout.addWidget(self.digitButton_5, 2, 1, 1, 1)
        self.digitButton_6 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_6.sizePolicy().hasHeightForWidth())
        self.digitButton_6.setSizePolicy(sizePolicy)
        self.digitButton_6.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_6.setText(_fromUtf8("6"))
        self.digitButton_6.setAutoRaise(True)
        self.digitButton_6.setObjectName(_fromUtf8("digitButton_6"))
        self.gridLayout.addWidget(self.digitButton_6, 2, 2, 1, 1)
        self.multiplyButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiplyButton.sizePolicy().hasHeightForWidth())
        self.multiplyButton.setSizePolicy(sizePolicy)
        self.multiplyButton.setMinimumSize(QtCore.QSize(24, 24))
        self.multiplyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.multiplyButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Multiply", None, QtGui.QApplication.UnicodeUTF8))
        self.multiplyButton.setText(_fromUtf8("×"))
        self.multiplyButton.setAutoRaise(True)
        self.multiplyButton.setObjectName(_fromUtf8("multiplyButton"))
        self.gridLayout.addWidget(self.multiplyButton, 2, 3, 1, 1)
        self.powerButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerButton.sizePolicy().hasHeightForWidth())
        self.powerButton.setSizePolicy(sizePolicy)
        self.powerButton.setMinimumSize(QtCore.QSize(24, 24))
        self.powerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.powerButton.setText(_fromUtf8("x²"))
        self.powerButton.setAutoRaise(True)
        self.powerButton.setObjectName(_fromUtf8("powerButton"))
        self.gridLayout.addWidget(self.powerButton, 2, 4, 1, 1)
        self.percentButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentButton.sizePolicy().hasHeightForWidth())
        self.percentButton.setSizePolicy(sizePolicy)
        self.percentButton.setMinimumSize(QtCore.QSize(24, 24))
        self.percentButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.percentButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.percentButton.setText(_fromUtf8("%"))
        self.percentButton.setAutoRaise(True)
        self.percentButton.setObjectName(_fromUtf8("percentButton"))
        self.gridLayout.addWidget(self.percentButton, 2, 5, 1, 1)
        self.digitButton_1 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_1.sizePolicy().hasHeightForWidth())
        self.digitButton_1.setSizePolicy(sizePolicy)
        self.digitButton_1.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_1.setText(_fromUtf8("1"))
        self.digitButton_1.setAutoRaise(True)
        self.digitButton_1.setObjectName(_fromUtf8("digitButton_1"))
        self.gridLayout.addWidget(self.digitButton_1, 3, 0, 1, 1)
        self.digitButton_2 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_2.sizePolicy().hasHeightForWidth())
        self.digitButton_2.setSizePolicy(sizePolicy)
        self.digitButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_2.setText(_fromUtf8("2"))
        self.digitButton_2.setAutoRaise(True)
        self.digitButton_2.setObjectName(_fromUtf8("digitButton_2"))
        self.gridLayout.addWidget(self.digitButton_2, 3, 1, 1, 1)
        self.digitButton_3 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_3.sizePolicy().hasHeightForWidth())
        self.digitButton_3.setSizePolicy(sizePolicy)
        self.digitButton_3.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_3.setText(_fromUtf8("3"))
        self.digitButton_3.setAutoRaise(True)
        self.digitButton_3.setObjectName(_fromUtf8("digitButton_3"))
        self.gridLayout.addWidget(self.digitButton_3, 3, 2, 1, 1)
        self.minusButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minusButton.sizePolicy().hasHeightForWidth())
        self.minusButton.setSizePolicy(sizePolicy)
        self.minusButton.setMinimumSize(QtCore.QSize(24, 24))
        self.minusButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.minusButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Minus", None, QtGui.QApplication.UnicodeUTF8))
        self.minusButton.setText(_fromUtf8("−"))
        self.minusButton.setAutoRaise(True)
        self.minusButton.setObjectName(_fromUtf8("minusButton"))
        self.gridLayout.addWidget(self.minusButton, 3, 3, 1, 1)
        self.reciprocalButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reciprocalButton.sizePolicy().hasHeightForWidth())
        self.reciprocalButton.setSizePolicy(sizePolicy)
        self.reciprocalButton.setMinimumSize(QtCore.QSize(24, 24))
        self.reciprocalButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reciprocalButton.setText(_fromUtf8("1/x"))
        self.reciprocalButton.setAutoRaise(True)
        self.reciprocalButton.setObjectName(_fromUtf8("reciprocalButton"))
        self.gridLayout.addWidget(self.reciprocalButton, 3, 4, 1, 1)
        self.clearButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(24, 24))
        self.clearButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Clear all (Delete)", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(_fromUtf8("C"))
        self.clearButton.setAutoRaise(True)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.gridLayout.addWidget(self.clearButton, 3, 5, 1, 1)
        self.changeSignButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeSignButton.sizePolicy().hasHeightForWidth())
        self.changeSignButton.setSizePolicy(sizePolicy)
        self.changeSignButton.setMinimumSize(QtCore.QSize(24, 24))
        self.changeSignButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.changeSignButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Change sign", None, QtGui.QApplication.UnicodeUTF8))
        self.changeSignButton.setText(_fromUtf8("±"))
        self.changeSignButton.setAutoRaise(True)
        self.changeSignButton.setObjectName(_fromUtf8("changeSignButton"))
        self.gridLayout.addWidget(self.changeSignButton, 4, 0, 1, 1)
        self.digitButton_0 = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digitButton_0.sizePolicy().hasHeightForWidth())
        self.digitButton_0.setSizePolicy(sizePolicy)
        self.digitButton_0.setMinimumSize(QtCore.QSize(24, 24))
        self.digitButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.digitButton_0.setText(_fromUtf8("0"))
        self.digitButton_0.setAutoRaise(True)
        self.digitButton_0.setObjectName(_fromUtf8("digitButton_0"))
        self.gridLayout.addWidget(self.digitButton_0, 4, 1, 1, 1)
        self.pointButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointButton.sizePolicy().hasHeightForWidth())
        self.pointButton.setSizePolicy(sizePolicy)
        self.pointButton.setMinimumSize(QtCore.QSize(24, 24))
        self.pointButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pointButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Decimal point", None, QtGui.QApplication.UnicodeUTF8))
        self.pointButton.setText(_fromUtf8("."))
        self.pointButton.setAutoRaise(True)
        self.pointButton.setObjectName(_fromUtf8("pointButton"))
        self.gridLayout.addWidget(self.pointButton, 4, 2, 1, 1)
        self.plusButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plusButton.sizePolicy().hasHeightForWidth())
        self.plusButton.setSizePolicy(sizePolicy)
        self.plusButton.setMinimumSize(QtCore.QSize(24, 24))
        self.plusButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plusButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Plus", None, QtGui.QApplication.UnicodeUTF8))
        self.plusButton.setText(_fromUtf8("+"))
        self.plusButton.setAutoRaise(True)
        self.plusButton.setObjectName(_fromUtf8("plusButton"))
        self.gridLayout.addWidget(self.plusButton, 4, 3, 1, 1)
        self.equalButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalButton.sizePolicy().hasHeightForWidth())
        self.equalButton.setSizePolicy(sizePolicy)
        self.equalButton.setMinimumSize(QtCore.QSize(24, 24))
        self.equalButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.equalButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Equal", None, QtGui.QApplication.UnicodeUTF8))
        self.equalButton.setText(_fromUtf8("="))
        self.equalButton.setAutoRaise(True)
        self.equalButton.setObjectName(_fromUtf8("equalButton"))
        self.gridLayout.addWidget(self.equalButton, 4, 4, 1, 1)
        self.okButton = QtGui.QToolButton(WPopupCalculator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QtCore.QSize(24, 24))
        self.okButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okButton.setToolTip(QtGui.QApplication.translate("WPopupCalculator", "Accept (Insert)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(_fromUtf8("OK"))
        self.okButton.setAutoRaise(True)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.gridLayout.addWidget(self.okButton, 4, 5, 1, 1)

        self.retranslateUi(WPopupCalculator)
        QtCore.QMetaObject.connectSlotsByName(WPopupCalculator)

    def retranslateUi(self, WPopupCalculator):
        pass

