# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\vic\wic\widgets\w_popup_time.ui'
#
# Created: Tue Feb 15 09:17:13 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_m_PopupTime(object):
    def setupUi(self, WPopupTime):
        WPopupTime.setObjectName(_fromUtf8("WPopupTime"))
        WPopupTime.setGeometry(QtCore.QRect(0, 0, 80, 228))
        WPopupTime.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout = QtGui.QGridLayout(WPopupTime)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.prevMonth = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth.sizePolicy().hasHeightForWidth())
        self.prevMonth.setSizePolicy(sizePolicy)
        self.prevMonth.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth.setAutoRepeat(False)
        self.prevMonth.setAutoRepeatDelay(300)
        self.prevMonth.setAutoRepeatInterval(100)
        self.prevMonth.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth.setAutoRaise(True)
        self.prevMonth.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth.setObjectName(_fromUtf8("prevMonth"))
        self.gridLayout.addWidget(self.prevMonth, 0, 0, 1, 1)
        self.prevMonth_14 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_14.sizePolicy().hasHeightForWidth())
        self.prevMonth_14.setSizePolicy(sizePolicy)
        self.prevMonth_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_14.setAutoRepeat(False)
        self.prevMonth_14.setAutoRepeatDelay(300)
        self.prevMonth_14.setAutoRepeatInterval(100)
        self.prevMonth_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_14.setAutoRaise(True)
        self.prevMonth_14.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_14.setObjectName(_fromUtf8("prevMonth_14"))
        self.gridLayout.addWidget(self.prevMonth_14, 0, 1, 1, 1)
        self.prevMonth_33 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_33.sizePolicy().hasHeightForWidth())
        self.prevMonth_33.setSizePolicy(sizePolicy)
        self.prevMonth_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_33.setAutoRepeat(False)
        self.prevMonth_33.setAutoRepeatDelay(300)
        self.prevMonth_33.setAutoRepeatInterval(100)
        self.prevMonth_33.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_33.setAutoRaise(True)
        self.prevMonth_33.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_33.setObjectName(_fromUtf8("prevMonth_33"))
        self.gridLayout.addWidget(self.prevMonth_33, 0, 2, 1, 1)
        self.prevMonth_2 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_2.sizePolicy().hasHeightForWidth())
        self.prevMonth_2.setSizePolicy(sizePolicy)
        self.prevMonth_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_2.setAutoRepeat(False)
        self.prevMonth_2.setAutoRepeatDelay(300)
        self.prevMonth_2.setAutoRepeatInterval(100)
        self.prevMonth_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_2.setAutoRaise(True)
        self.prevMonth_2.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_2.setObjectName(_fromUtf8("prevMonth_2"))
        self.gridLayout.addWidget(self.prevMonth_2, 1, 0, 1, 1)
        self.prevMonth_21 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_21.sizePolicy().hasHeightForWidth())
        self.prevMonth_21.setSizePolicy(sizePolicy)
        self.prevMonth_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_21.setAutoRepeat(False)
        self.prevMonth_21.setAutoRepeatDelay(300)
        self.prevMonth_21.setAutoRepeatInterval(100)
        self.prevMonth_21.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_21.setAutoRaise(True)
        self.prevMonth_21.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_21.setObjectName(_fromUtf8("prevMonth_21"))
        self.gridLayout.addWidget(self.prevMonth_21, 1, 1, 1, 1)
        self.prevMonth_30 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_30.sizePolicy().hasHeightForWidth())
        self.prevMonth_30.setSizePolicy(sizePolicy)
        self.prevMonth_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_30.setAutoRepeat(False)
        self.prevMonth_30.setAutoRepeatDelay(300)
        self.prevMonth_30.setAutoRepeatInterval(100)
        self.prevMonth_30.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_30.setAutoRaise(True)
        self.prevMonth_30.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_30.setObjectName(_fromUtf8("prevMonth_30"))
        self.gridLayout.addWidget(self.prevMonth_30, 1, 2, 1, 1)
        self.prevMonth_3 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_3.sizePolicy().hasHeightForWidth())
        self.prevMonth_3.setSizePolicy(sizePolicy)
        self.prevMonth_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_3.setAutoRepeat(False)
        self.prevMonth_3.setAutoRepeatDelay(300)
        self.prevMonth_3.setAutoRepeatInterval(100)
        self.prevMonth_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_3.setAutoRaise(True)
        self.prevMonth_3.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_3.setObjectName(_fromUtf8("prevMonth_3"))
        self.gridLayout.addWidget(self.prevMonth_3, 2, 0, 1, 1)
        self.prevMonth_19 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_19.sizePolicy().hasHeightForWidth())
        self.prevMonth_19.setSizePolicy(sizePolicy)
        self.prevMonth_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_19.setAutoRepeat(False)
        self.prevMonth_19.setAutoRepeatDelay(300)
        self.prevMonth_19.setAutoRepeatInterval(100)
        self.prevMonth_19.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_19.setAutoRaise(True)
        self.prevMonth_19.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_19.setObjectName(_fromUtf8("prevMonth_19"))
        self.gridLayout.addWidget(self.prevMonth_19, 2, 1, 1, 1)
        self.prevMonth_31 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_31.sizePolicy().hasHeightForWidth())
        self.prevMonth_31.setSizePolicy(sizePolicy)
        self.prevMonth_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_31.setAutoRepeat(False)
        self.prevMonth_31.setAutoRepeatDelay(300)
        self.prevMonth_31.setAutoRepeatInterval(100)
        self.prevMonth_31.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_31.setAutoRaise(True)
        self.prevMonth_31.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_31.setObjectName(_fromUtf8("prevMonth_31"))
        self.gridLayout.addWidget(self.prevMonth_31, 2, 2, 1, 1)
        self.prevMonth_4 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_4.sizePolicy().hasHeightForWidth())
        self.prevMonth_4.setSizePolicy(sizePolicy)
        self.prevMonth_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_4.setAutoRepeat(False)
        self.prevMonth_4.setAutoRepeatDelay(300)
        self.prevMonth_4.setAutoRepeatInterval(100)
        self.prevMonth_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_4.setAutoRaise(True)
        self.prevMonth_4.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_4.setObjectName(_fromUtf8("prevMonth_4"))
        self.gridLayout.addWidget(self.prevMonth_4, 3, 0, 1, 1)
        self.prevMonth_22 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_22.sizePolicy().hasHeightForWidth())
        self.prevMonth_22.setSizePolicy(sizePolicy)
        self.prevMonth_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_22.setAutoRepeat(False)
        self.prevMonth_22.setAutoRepeatDelay(300)
        self.prevMonth_22.setAutoRepeatInterval(100)
        self.prevMonth_22.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_22.setAutoRaise(True)
        self.prevMonth_22.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_22.setObjectName(_fromUtf8("prevMonth_22"))
        self.gridLayout.addWidget(self.prevMonth_22, 3, 1, 1, 1)
        self.prevMonth_36 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_36.sizePolicy().hasHeightForWidth())
        self.prevMonth_36.setSizePolicy(sizePolicy)
        self.prevMonth_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_36.setAutoRepeat(False)
        self.prevMonth_36.setAutoRepeatDelay(300)
        self.prevMonth_36.setAutoRepeatInterval(100)
        self.prevMonth_36.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_36.setAutoRaise(True)
        self.prevMonth_36.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_36.setObjectName(_fromUtf8("prevMonth_36"))
        self.gridLayout.addWidget(self.prevMonth_36, 3, 2, 1, 1)
        self.prevMonth_5 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_5.sizePolicy().hasHeightForWidth())
        self.prevMonth_5.setSizePolicy(sizePolicy)
        self.prevMonth_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_5.setAutoRepeat(False)
        self.prevMonth_5.setAutoRepeatDelay(300)
        self.prevMonth_5.setAutoRepeatInterval(100)
        self.prevMonth_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_5.setAutoRaise(True)
        self.prevMonth_5.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_5.setObjectName(_fromUtf8("prevMonth_5"))
        self.gridLayout.addWidget(self.prevMonth_5, 4, 0, 1, 1)
        self.prevMonth_20 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_20.sizePolicy().hasHeightForWidth())
        self.prevMonth_20.setSizePolicy(sizePolicy)
        self.prevMonth_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_20.setAutoRepeat(False)
        self.prevMonth_20.setAutoRepeatDelay(300)
        self.prevMonth_20.setAutoRepeatInterval(100)
        self.prevMonth_20.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_20.setAutoRaise(True)
        self.prevMonth_20.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_20.setObjectName(_fromUtf8("prevMonth_20"))
        self.gridLayout.addWidget(self.prevMonth_20, 4, 1, 1, 1)
        self.prevMonth_37 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_37.sizePolicy().hasHeightForWidth())
        self.prevMonth_37.setSizePolicy(sizePolicy)
        self.prevMonth_37.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_37.setAutoRepeat(False)
        self.prevMonth_37.setAutoRepeatDelay(300)
        self.prevMonth_37.setAutoRepeatInterval(100)
        self.prevMonth_37.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_37.setAutoRaise(True)
        self.prevMonth_37.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_37.setObjectName(_fromUtf8("prevMonth_37"))
        self.gridLayout.addWidget(self.prevMonth_37, 4, 2, 1, 1)
        self.prevMonth_6 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_6.sizePolicy().hasHeightForWidth())
        self.prevMonth_6.setSizePolicy(sizePolicy)
        self.prevMonth_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_6.setAutoRepeat(False)
        self.prevMonth_6.setAutoRepeatDelay(300)
        self.prevMonth_6.setAutoRepeatInterval(100)
        self.prevMonth_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_6.setAutoRaise(True)
        self.prevMonth_6.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_6.setObjectName(_fromUtf8("prevMonth_6"))
        self.gridLayout.addWidget(self.prevMonth_6, 5, 0, 1, 1)
        self.prevMonth_25 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_25.sizePolicy().hasHeightForWidth())
        self.prevMonth_25.setSizePolicy(sizePolicy)
        self.prevMonth_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_25.setAutoRepeat(False)
        self.prevMonth_25.setAutoRepeatDelay(300)
        self.prevMonth_25.setAutoRepeatInterval(100)
        self.prevMonth_25.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_25.setAutoRaise(True)
        self.prevMonth_25.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_25.setObjectName(_fromUtf8("prevMonth_25"))
        self.gridLayout.addWidget(self.prevMonth_25, 5, 1, 1, 1)
        self.prevMonth_34 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_34.sizePolicy().hasHeightForWidth())
        self.prevMonth_34.setSizePolicy(sizePolicy)
        self.prevMonth_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_34.setAutoRepeat(False)
        self.prevMonth_34.setAutoRepeatDelay(300)
        self.prevMonth_34.setAutoRepeatInterval(100)
        self.prevMonth_34.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_34.setAutoRaise(True)
        self.prevMonth_34.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_34.setObjectName(_fromUtf8("prevMonth_34"))
        self.gridLayout.addWidget(self.prevMonth_34, 5, 2, 1, 1)
        self.prevMonth_7 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_7.sizePolicy().hasHeightForWidth())
        self.prevMonth_7.setSizePolicy(sizePolicy)
        self.prevMonth_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_7.setAutoRepeat(False)
        self.prevMonth_7.setAutoRepeatDelay(300)
        self.prevMonth_7.setAutoRepeatInterval(100)
        self.prevMonth_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_7.setAutoRaise(True)
        self.prevMonth_7.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_7.setObjectName(_fromUtf8("prevMonth_7"))
        self.gridLayout.addWidget(self.prevMonth_7, 6, 0, 1, 1)
        self.prevMonth_23 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_23.sizePolicy().hasHeightForWidth())
        self.prevMonth_23.setSizePolicy(sizePolicy)
        self.prevMonth_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_23.setAutoRepeat(False)
        self.prevMonth_23.setAutoRepeatDelay(300)
        self.prevMonth_23.setAutoRepeatInterval(100)
        self.prevMonth_23.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_23.setAutoRaise(True)
        self.prevMonth_23.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_23.setObjectName(_fromUtf8("prevMonth_23"))
        self.gridLayout.addWidget(self.prevMonth_23, 6, 1, 1, 1)
        self.prevMonth_38 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_38.sizePolicy().hasHeightForWidth())
        self.prevMonth_38.setSizePolicy(sizePolicy)
        self.prevMonth_38.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_38.setAutoRepeat(False)
        self.prevMonth_38.setAutoRepeatDelay(300)
        self.prevMonth_38.setAutoRepeatInterval(100)
        self.prevMonth_38.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_38.setAutoRaise(True)
        self.prevMonth_38.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_38.setObjectName(_fromUtf8("prevMonth_38"))
        self.gridLayout.addWidget(self.prevMonth_38, 6, 2, 1, 1)
        self.prevMonth_8 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_8.sizePolicy().hasHeightForWidth())
        self.prevMonth_8.setSizePolicy(sizePolicy)
        self.prevMonth_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_8.setAutoRepeat(False)
        self.prevMonth_8.setAutoRepeatDelay(300)
        self.prevMonth_8.setAutoRepeatInterval(100)
        self.prevMonth_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_8.setAutoRaise(True)
        self.prevMonth_8.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_8.setObjectName(_fromUtf8("prevMonth_8"))
        self.gridLayout.addWidget(self.prevMonth_8, 7, 0, 1, 1)
        self.prevMonth_26 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_26.sizePolicy().hasHeightForWidth())
        self.prevMonth_26.setSizePolicy(sizePolicy)
        self.prevMonth_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_26.setAutoRepeat(False)
        self.prevMonth_26.setAutoRepeatDelay(300)
        self.prevMonth_26.setAutoRepeatInterval(100)
        self.prevMonth_26.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_26.setAutoRaise(True)
        self.prevMonth_26.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_26.setObjectName(_fromUtf8("prevMonth_26"))
        self.gridLayout.addWidget(self.prevMonth_26, 7, 1, 1, 1)
        self.prevMonth_28 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_28.sizePolicy().hasHeightForWidth())
        self.prevMonth_28.setSizePolicy(sizePolicy)
        self.prevMonth_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_28.setAutoRepeat(False)
        self.prevMonth_28.setAutoRepeatDelay(300)
        self.prevMonth_28.setAutoRepeatInterval(100)
        self.prevMonth_28.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_28.setAutoRaise(True)
        self.prevMonth_28.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_28.setObjectName(_fromUtf8("prevMonth_28"))
        self.gridLayout.addWidget(self.prevMonth_28, 7, 2, 1, 1)
        self.prevMonth_9 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_9.sizePolicy().hasHeightForWidth())
        self.prevMonth_9.setSizePolicy(sizePolicy)
        self.prevMonth_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_9.setAutoRepeat(False)
        self.prevMonth_9.setAutoRepeatDelay(300)
        self.prevMonth_9.setAutoRepeatInterval(100)
        self.prevMonth_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_9.setAutoRaise(True)
        self.prevMonth_9.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_9.setObjectName(_fromUtf8("prevMonth_9"))
        self.gridLayout.addWidget(self.prevMonth_9, 8, 0, 1, 1)
        self.prevMonth_16 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_16.sizePolicy().hasHeightForWidth())
        self.prevMonth_16.setSizePolicy(sizePolicy)
        self.prevMonth_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_16.setAutoRepeat(False)
        self.prevMonth_16.setAutoRepeatDelay(300)
        self.prevMonth_16.setAutoRepeatInterval(100)
        self.prevMonth_16.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_16.setAutoRaise(True)
        self.prevMonth_16.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_16.setObjectName(_fromUtf8("prevMonth_16"))
        self.gridLayout.addWidget(self.prevMonth_16, 8, 1, 1, 1)
        self.prevMonth_35 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_35.sizePolicy().hasHeightForWidth())
        self.prevMonth_35.setSizePolicy(sizePolicy)
        self.prevMonth_35.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_35.setAutoRepeat(False)
        self.prevMonth_35.setAutoRepeatDelay(300)
        self.prevMonth_35.setAutoRepeatInterval(100)
        self.prevMonth_35.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_35.setAutoRaise(True)
        self.prevMonth_35.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_35.setObjectName(_fromUtf8("prevMonth_35"))
        self.gridLayout.addWidget(self.prevMonth_35, 8, 2, 1, 1)
        self.prevMonth_10 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_10.sizePolicy().hasHeightForWidth())
        self.prevMonth_10.setSizePolicy(sizePolicy)
        self.prevMonth_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_10.setAutoRepeat(False)
        self.prevMonth_10.setAutoRepeatDelay(300)
        self.prevMonth_10.setAutoRepeatInterval(100)
        self.prevMonth_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_10.setAutoRaise(True)
        self.prevMonth_10.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_10.setObjectName(_fromUtf8("prevMonth_10"))
        self.gridLayout.addWidget(self.prevMonth_10, 9, 0, 1, 1)
        self.prevMonth_18 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_18.sizePolicy().hasHeightForWidth())
        self.prevMonth_18.setSizePolicy(sizePolicy)
        self.prevMonth_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_18.setAutoRepeat(False)
        self.prevMonth_18.setAutoRepeatDelay(300)
        self.prevMonth_18.setAutoRepeatInterval(100)
        self.prevMonth_18.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_18.setAutoRaise(True)
        self.prevMonth_18.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_18.setObjectName(_fromUtf8("prevMonth_18"))
        self.gridLayout.addWidget(self.prevMonth_18, 9, 1, 1, 1)
        self.prevMonth_32 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_32.sizePolicy().hasHeightForWidth())
        self.prevMonth_32.setSizePolicy(sizePolicy)
        self.prevMonth_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_32.setAutoRepeat(False)
        self.prevMonth_32.setAutoRepeatDelay(300)
        self.prevMonth_32.setAutoRepeatInterval(100)
        self.prevMonth_32.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_32.setAutoRaise(True)
        self.prevMonth_32.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_32.setObjectName(_fromUtf8("prevMonth_32"))
        self.gridLayout.addWidget(self.prevMonth_32, 9, 2, 1, 1)
        self.prevMonth_11 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_11.sizePolicy().hasHeightForWidth())
        self.prevMonth_11.setSizePolicy(sizePolicy)
        self.prevMonth_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_11.setAutoRepeat(False)
        self.prevMonth_11.setAutoRepeatDelay(300)
        self.prevMonth_11.setAutoRepeatInterval(100)
        self.prevMonth_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_11.setAutoRaise(True)
        self.prevMonth_11.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_11.setObjectName(_fromUtf8("prevMonth_11"))
        self.gridLayout.addWidget(self.prevMonth_11, 10, 0, 1, 1)
        self.prevMonth_15 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_15.sizePolicy().hasHeightForWidth())
        self.prevMonth_15.setSizePolicy(sizePolicy)
        self.prevMonth_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_15.setAutoRepeat(False)
        self.prevMonth_15.setAutoRepeatDelay(300)
        self.prevMonth_15.setAutoRepeatInterval(100)
        self.prevMonth_15.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_15.setAutoRaise(True)
        self.prevMonth_15.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_15.setObjectName(_fromUtf8("prevMonth_15"))
        self.gridLayout.addWidget(self.prevMonth_15, 10, 1, 1, 1)
        self.prevMonth_39 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_39.sizePolicy().hasHeightForWidth())
        self.prevMonth_39.setSizePolicy(sizePolicy)
        self.prevMonth_39.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_39.setAutoRepeat(False)
        self.prevMonth_39.setAutoRepeatDelay(300)
        self.prevMonth_39.setAutoRepeatInterval(100)
        self.prevMonth_39.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_39.setAutoRaise(True)
        self.prevMonth_39.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_39.setObjectName(_fromUtf8("prevMonth_39"))
        self.gridLayout.addWidget(self.prevMonth_39, 10, 2, 1, 1)
        self.prevMonth_12 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_12.sizePolicy().hasHeightForWidth())
        self.prevMonth_12.setSizePolicy(sizePolicy)
        self.prevMonth_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_12.setAutoRepeat(False)
        self.prevMonth_12.setAutoRepeatDelay(300)
        self.prevMonth_12.setAutoRepeatInterval(100)
        self.prevMonth_12.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_12.setAutoRaise(True)
        self.prevMonth_12.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_12.setObjectName(_fromUtf8("prevMonth_12"))
        self.gridLayout.addWidget(self.prevMonth_12, 11, 0, 1, 1)
        self.prevMonth_17 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_17.sizePolicy().hasHeightForWidth())
        self.prevMonth_17.setSizePolicy(sizePolicy)
        self.prevMonth_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_17.setAutoRepeat(False)
        self.prevMonth_17.setAutoRepeatDelay(300)
        self.prevMonth_17.setAutoRepeatInterval(100)
        self.prevMonth_17.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_17.setAutoRaise(True)
        self.prevMonth_17.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_17.setObjectName(_fromUtf8("prevMonth_17"))
        self.gridLayout.addWidget(self.prevMonth_17, 11, 1, 1, 1)
        self.prevMonth_29 = QtGui.QToolButton(WPopupTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth_29.sizePolicy().hasHeightForWidth())
        self.prevMonth_29.setSizePolicy(sizePolicy)
        self.prevMonth_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth_29.setAutoRepeat(False)
        self.prevMonth_29.setAutoRepeatDelay(300)
        self.prevMonth_29.setAutoRepeatInterval(100)
        self.prevMonth_29.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth_29.setAutoRaise(True)
        self.prevMonth_29.setArrowType(QtCore.Qt.LeftArrow)
        self.prevMonth_29.setObjectName(_fromUtf8("prevMonth_29"))
        self.gridLayout.addWidget(self.prevMonth_29, 11, 2, 1, 1)

        self.retranslateUi(WPopupTime)
        QtCore.QMetaObject.connectSlotsByName(WPopupTime)

    def retranslateUi(self, WPopupTime):
        WPopupTime.setWindowTitle(QtGui.QApplication.translate("m_PopupTime", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth.setText(QtGui.QApplication.translate("m_PopupTime", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_14.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_14.setText(QtGui.QApplication.translate("m_PopupTime", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_33.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_33.setText(QtGui.QApplication.translate("m_PopupTime", ":00", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_2.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_2.setText(QtGui.QApplication.translate("m_PopupTime", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_21.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_21.setText(QtGui.QApplication.translate("m_PopupTime", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_30.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_30.setText(QtGui.QApplication.translate("m_PopupTime", ":05", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_3.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_3.setText(QtGui.QApplication.translate("m_PopupTime", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_19.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_19.setText(QtGui.QApplication.translate("m_PopupTime", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_31.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_31.setText(QtGui.QApplication.translate("m_PopupTime", ":10", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_4.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_4.setText(QtGui.QApplication.translate("m_PopupTime", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_22.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_22.setText(QtGui.QApplication.translate("m_PopupTime", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_36.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_36.setText(QtGui.QApplication.translate("m_PopupTime", ":15", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_5.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_5.setText(QtGui.QApplication.translate("m_PopupTime", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_20.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_20.setText(QtGui.QApplication.translate("m_PopupTime", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_37.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_37.setText(QtGui.QApplication.translate("m_PopupTime", ":20", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_6.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_6.setText(QtGui.QApplication.translate("m_PopupTime", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_25.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_25.setText(QtGui.QApplication.translate("m_PopupTime", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_34.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_34.setText(QtGui.QApplication.translate("m_PopupTime", ":25", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_7.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_7.setText(QtGui.QApplication.translate("m_PopupTime", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_23.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_23.setText(QtGui.QApplication.translate("m_PopupTime", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_38.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_38.setText(QtGui.QApplication.translate("m_PopupTime", ":30", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_8.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_8.setText(QtGui.QApplication.translate("m_PopupTime", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_26.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_26.setText(QtGui.QApplication.translate("m_PopupTime", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_28.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_28.setText(QtGui.QApplication.translate("m_PopupTime", ":35", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_9.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_9.setText(QtGui.QApplication.translate("m_PopupTime", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_16.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_16.setText(QtGui.QApplication.translate("m_PopupTime", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_35.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_35.setText(QtGui.QApplication.translate("m_PopupTime", ":40", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_10.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_10.setText(QtGui.QApplication.translate("m_PopupTime", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_18.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_18.setText(QtGui.QApplication.translate("m_PopupTime", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_32.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_32.setText(QtGui.QApplication.translate("m_PopupTime", ":45", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_11.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_11.setText(QtGui.QApplication.translate("m_PopupTime", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_15.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_15.setText(QtGui.QApplication.translate("m_PopupTime", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_39.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_39.setText(QtGui.QApplication.translate("m_PopupTime", ":50", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_12.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_12.setText(QtGui.QApplication.translate("m_PopupTime", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_17.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_17.setText(QtGui.QApplication.translate("m_PopupTime", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_29.setToolTip(QtGui.QApplication.translate("m_PopupTime", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth_29.setText(QtGui.QApplication.translate("m_PopupTime", ":55", None, QtGui.QApplication.UnicodeUTF8))

import m_widgets_rc
