# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vic/Desktop/wic/widgets/w_popup_calendar.ui'
#
# Created: Tue Sep 13 20:28:53 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WPopupCalendar(object):
    def setupUi(self, WPopupCalendar):
        WPopupCalendar.setObjectName(_fromUtf8("WPopupCalendar"))
        WPopupCalendar.resize(266, 172)
        WPopupCalendar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        WPopupCalendar.setWindowTitle(QtGui.QApplication.translate("WPopupCalendar", "Календарь", None, QtGui.QApplication.UnicodeUTF8))
        WPopupCalendar.setStyleSheet(_fromUtf8("background-color: rgb(245, 245, 245);"))
        self.gridLayout = QtGui.QGridLayout(WPopupCalendar)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.date = QtGui.QToolButton(WPopupCalendar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        self.date.setMinimumSize(QtCore.QSize(95, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.date.setFont(font)
        self.date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date.setFocusPolicy(QtCore.Qt.NoFocus)
        self.date.setToolTip(QtGui.QApplication.translate("WPopupCalendar", "Special date", "Select special date", QtGui.QApplication.UnicodeUTF8))
        self.date.setText(QtGui.QApplication.translate("WPopupCalendar", "Selected date", None, QtGui.QApplication.UnicodeUTF8))
        self.date.setAutoRaise(True)
        self.date.setArrowType(QtCore.Qt.NoArrow)
        self.date.setObjectName(_fromUtf8("date"))
        self.gridLayout.addWidget(self.date, 0, 0, 1, 1)
        self.prevMonth = QtGui.QToolButton(WPopupCalendar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonth.sizePolicy().hasHeightForWidth())
        self.prevMonth.setSizePolicy(sizePolicy)
        self.prevMonth.setMinimumSize(QtCore.QSize(20, 22))
        self.prevMonth.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonth.setToolTip(QtGui.QApplication.translate("WPopupCalendar", "Previous month", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth.setText(QtGui.QApplication.translate("WPopupCalendar", "‹", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMonth.setAutoRepeat(True)
        self.prevMonth.setAutoRepeatDelay(300)
        self.prevMonth.setAutoRepeatInterval(100)
        self.prevMonth.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevMonth.setAutoRaise(True)
        self.prevMonth.setObjectName(_fromUtf8("prevMonth"))
        self.gridLayout.addWidget(self.prevMonth, 0, 1, 1, 1)
        self.nextMonth = QtGui.QToolButton(WPopupCalendar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextMonth.sizePolicy().hasHeightForWidth())
        self.nextMonth.setSizePolicy(sizePolicy)
        self.nextMonth.setMinimumSize(QtCore.QSize(20, 22))
        self.nextMonth.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextMonth.setToolTip(QtGui.QApplication.translate("WPopupCalendar", "Next month", None, QtGui.QApplication.UnicodeUTF8))
        self.nextMonth.setText(QtGui.QApplication.translate("WPopupCalendar", "›", None, QtGui.QApplication.UnicodeUTF8))
        self.nextMonth.setAutoRepeat(True)
        self.nextMonth.setAutoRepeatDelay(300)
        self.nextMonth.setAutoRepeatInterval(100)
        self.nextMonth.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.nextMonth.setAutoRaise(True)
        self.nextMonth.setObjectName(_fromUtf8("nextMonth"))
        self.gridLayout.addWidget(self.nextMonth, 0, 2, 1, 1)
        self.prevYear = QtGui.QToolButton(WPopupCalendar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevYear.sizePolicy().hasHeightForWidth())
        self.prevYear.setSizePolicy(sizePolicy)
        self.prevYear.setMinimumSize(QtCore.QSize(20, 22))
        self.prevYear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevYear.setToolTip(QtGui.QApplication.translate("WPopupCalendar", "Previous year", None, QtGui.QApplication.UnicodeUTF8))
        self.prevYear.setText(QtGui.QApplication.translate("WPopupCalendar", "‹‹", None, QtGui.QApplication.UnicodeUTF8))
        self.prevYear.setAutoRepeat(True)
        self.prevYear.setAutoRepeatInterval(200)
        self.prevYear.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.prevYear.setAutoRaise(True)
        self.prevYear.setObjectName(_fromUtf8("prevYear"))
        self.gridLayout.addWidget(self.prevYear, 0, 3, 1, 1)
        self.nextYear = QtGui.QToolButton(WPopupCalendar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextYear.sizePolicy().hasHeightForWidth())
        self.nextYear.setSizePolicy(sizePolicy)
        self.nextYear.setMinimumSize(QtCore.QSize(20, 22))
        self.nextYear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextYear.setToolTip(QtGui.QApplication.translate("WPopupCalendar", "Next year", None, QtGui.QApplication.UnicodeUTF8))
        self.nextYear.setText(QtGui.QApplication.translate("WPopupCalendar", "››", None, QtGui.QApplication.UnicodeUTF8))
        self.nextYear.setAutoRepeat(True)
        self.nextYear.setAutoRepeatInterval(200)
        self.nextYear.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.nextYear.setAutoRaise(True)
        self.nextYear.setObjectName(_fromUtf8("nextYear"))
        self.gridLayout.addWidget(self.nextYear, 0, 4, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(WPopupCalendar)
        self.calendarWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.calendarWidget.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setHorizontalHeaderFormat(QtGui.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(False)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.gridLayout.addWidget(self.calendarWidget, 1, 0, 1, 5)
        self.gridLayout.setColumnStretch(0, 5)

        self.retranslateUi(WPopupCalendar)
        QtCore.QMetaObject.connectSlotsByName(WPopupCalendar)

    def retranslateUi(self, WPopupCalendar):
        pass

