import os, sys, importlib
from PyQt4 import QtGui, QtCore, uic
from wic.widgets.w_date_edit import WDateEdit
from wic.widgets.w_decimal_edit import WDecimalEdit
import orm
import wic


class WForm(QtGui.QDialog):
    '''Base for user forms.'''
    
    uiFilePath = 'form.ui' # absolute or relative path to the ui file
    iconPath = ':/icons/fugue/application-form.png'
    formTitle = 'Form'
    
    closed = QtCore.pyqtSignal() # emitted when the form is closing
    
    def __init__(self, parentWidget):
        super().__init__(parentWidget)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        
        if self.uiFilePath: # not autogenerated
            if os.path.isabs(self.uiFilePath):
                uiFilePath = self.uiFilePath
            else: # ui file path is relative. extract module path
                moduleName = self.__class__.__module__
                module = sys.modules[moduleName] # module in which the Form class was defined
                moduleDir = os.path.dirname(os.path.abspath(module.__file__)) 
                self.uiFilePath = os.path.join(moduleDir, self.uiFilePath)
        
        self.setupUi()
        
        self.on_open()
        
    def setupUi(self):
        '''Initial setting up of the form. 
        Catalog item forms fill form fields with data from DB.'''
        self.setWindowTitle(self.formTitle)
        self.setWindowIcon(QtGui.QIcon(self.iconPath))
        if self.uiFilePath: # not autogenerated
            uic.loadUi(self.uiFilePath, self)

    def done(self, resultCode): # accept/reject by default bypasses closeEvent
        super().done(resultCode)
        self.close()

    def closeEvent(self, event):
        if self.on_close() == False: # вызов предопределенной процедуры
            event.ignore()
            return
        self.closed.emit()
        #self.reject()

    def on_close(self):
        return

    def on_open(self):
        return
    


def openForm(formModulePath, formClassName= 'Form'):
    formModule = importlib.import_module(formModulePath)
    FormClass = getattr(formModule, formClassName)
    assert issubclass(FormClass, WForm), 'This is not a WForm.'
    form = FormClass(None) # no parent widget for now
    window = wic.mainWindow.mdiArea.addSubWindow(form) # create subwindow with the form
    window.setWindowIcon(form.windowIcon())
    window.show()
    form.closed.connect(window.close) # when form closes - close subwindow too            


def openCatalogItemForm(catalogItem, formClassName= 'Form'):
    assert isinstance(catalogItem, orm.Model), 'Pass an item (model instance).'
    formModulePath = catalogItem.__class__.__module__
    
    formModule = importlib.import_module(formModulePath)
    FormClass = getattr(formModule, formClassName)
    assert issubclass(FormClass, CatalogForm), 'This is not a CatalogForm: %s - %s' % (formModulePath, formClassName)
    form = FormClass(None, catalogItem) # no parent widget for now
    window = wic.mainWindow.mdiArea.addSubWindow(form) # create subwindow with the form
    window.setWindowIcon(form.windowIcon())
    window.show()
    form.closed.connect(window.close) # when form closes - close subwindow too            



class CatalogForm(WForm):
    '''Form of a catalog item.'''
    formTitle = 'Catalog item'
    iconPath = ':/icons/fugue/card-address.png'
    catalogItem = None
    
    def __init__(self, parentWidget, catalogItem):
        self.catalogItem = catalogItem
        super().__init__(parentWidget)

    def setupUi(self):
        '''Initial setting up of the form.
        Dynamically create form fields, if no ui file is supplied. 
        Fill form fields with data from DB.'''
        catalogItem = self.catalogItem
        self.formTitle = '%s item' % catalogItem.__class__ 
        super().setupUi()
        if not self.uiFilePath: # automatically generated form
            self.formLayout = QtGui.QFormLayout(self)
            formLayout = self.formLayout
            formLayout.setMargin(2)
            formLayout.setObjectName('formLayout')
            for field in catalogItem.__class__:
                fieldName = field.name
                assert not hasattr(self, fieldName), 'Form already has attribute with name ""%s' % fieldName
                labelName = 'label_' + fieldName
                label = QtGui.QLabel(fieldName)
                label.setObjectName(labelName)
                #widget = QtGui.QLineEdit()
                widget = createWidgetFromField(field)
                #widget.setObjectName(fieldName)
                setattr(self, fieldName, widget)
                label.setBuddy(widget)
                formLayout.addRow(label, widget)
            
            buttonBox = QtGui.QDialogButtonBox(QtGui.QDialogButtonBox.Reset | QtGui.QDialogButtonBox.Save | QtGui.QDialogButtonBox.Cancel)
            saveButton = buttonBox.button(buttonBox.Save)
            buttonBox.addButton(saveButton, buttonBox.ApplyRole)
            saveButton.clicked.connect(self.save)
            buttonBox.rejected.connect(self.reject)
            formLayout.addRow(buttonBox)
            saveShortCut = QtGui.QShortcut(QtGui.QKeySequence('F2'), self)
            saveShortCut.activated.connect(saveButton.animateClick)
            resetButton = buttonBox.button(buttonBox.Reset)
            resetButton.clicked.connect(self.fillFormFromItem)
            
        self.fillFormFromItem()

    def fillFormFromItem(self):
        'Automatically fill the form fields using values from the catalog item fields.'
        catalogItem = self.catalogItem
        for field in catalogItem.__class__:
            fieldName = field.name
            fieldValue = catalogItem[field]
            widget = getattr(self, fieldName)
            setValue(widget, fieldValue)
        
            
    def save(self):
        ''
        wic.w.printMessage('save!')


        
def createWidgetFromField(field):
    assert isinstance(field, orm.Field), 'Pass a Field instance.'
    if isinstance(field, orm.StringField):
        widget = QtGui.QLineEdit()
        widget.setMaxLength(field.maxLength)
    elif isinstance(field, (orm.IntegerField, orm.IdField)):
        widget = QtGui.QLineEdit()
        widget.setValidator(QtGui.QIntValidator())
    else:
        raise Exception('Could not find a widget for field %s' % field)
    return widget

def setValue(widget, value):
    '''Set value of a widget.'''        
    if isinstance(widget, QtGui.QTextEdit): 
        widget.setPlainText(str(value))
    elif isinstance(widget, QtGui.QCheckBox): 
        #widget.blockSignals(True) # http://stackoverflow.com/questions/1856544/qcheckbox-is-it-really-not-possible-to-differentiate-between-user-induced-change
        widget.setChecked(value)
        #widget.blockSignals(False) 
    elif isinstance(widget, (WDateEdit, WDecimalEdit, QtGui.QSpinBox)):
        widget.setValue(value)
    elif isinstance(widget, (QtGui.QLineEdit, QtGui.QPushButton)): 
        widget.setText(str(value))

def getValue(widget):
    if isinstance(widget, QtGui.QTextEdit): 
        return widget.plainText()
    elif isinstance(widget, QtGui.QCheckBox): 
        return widget.isChecked()
    elif isinstance(widget, (WDateEdit, WDecimalEdit)): 
        return widget.value
    elif isinstance(widget, QtGui.QSpinBox): 
        return widget.value()
    elif isinstance(widget, (QtGui.QLineEdit, QtGui.QPushButton)): 
        return widget.text()


def putToForm(data, uiFilePath, dialog):
    'Загрузить форму с диска, заполнить поля данными data и вернуть форму'
    dialog = uic.loadUi(uiFilePath, QtGui.QDialog(dialog))
    for name, value in data.items():
        try: widget = getattr(dialog, name) # ищем нужный атрибут на форме
        except AttributeError: continue # такого нет
        if isinstance(widget, QtGui.QLineEdit):
            widget.setText(value)
            widget.home(False)
        elif isinstance(widget, QtGui.QPlainTextEdit):
            widget.setPlainText(value)
        elif isinstance(widget, QtGui.QLabel):
            widget.setText(value)
        elif isinstance(widget, QtGui.QComboBox):
            lineEdit = widget.lineEdit()
            if lineEdit: #Only editable combo boxes have a line edit
                lineEdit.setText(value)
        elif isinstance(widget, QtGui.QSpinBox):
            widget.setValue(int(value))
        elif isinstance(widget, QtGui.QCheckBox):
            widget.setChecked(value)
    return dialog


def getFromForm(dialog):
    data = {}
    for widget in dialog.children():
        value = None
        if isinstance(widget, QtGui.QLineEdit):
            value = widget.text()
        elif isinstance(widget, QtGui.QPlainTextEdit):
            value = widget.toPlainText()
        elif isinstance(widget, QtGui.QComboBox):
            lineEdit = widget.lineEdit()
            if lineEdit: #Only editable combo boxes have a line edit
                value = lineEdit.text()
        elif isinstance(widget, QtGui.QSpinBox):
            value = widget.value()
        elif isinstance(widget, QtGui.QCheckBox):
            value = bool(widget.isChecked())
        if value is not None:
            data[widget.objectName()] = value
    return data

